# Generated by Django 5.1.5 on 2025-01-30 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetaContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('keywords', models.TextField(verbose_name='Ключевые слова')),
            ],
            options={
                'verbose_name': 'Метатеги',
                'verbose_name_plural': 'Метатеги',
            },
        ),
    ]
