# Generated by Django 5.1.5 on 2025-01-30 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SideBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engineer_text', models.CharField(max_length=255, verbose_name='Текст кнопки вызова инженера')),
                ('price_text', models.CharField(max_length=255, verbose_name='Текст кнопки скачивания прайса')),
                ('whatsapp_text', models.CharField(max_length=255, verbose_name='Текст кнопки WhatsApp')),
                ('price_link', models.URLField(verbose_name='Ссылка на прайс')),
                ('whatsapp_link', models.URLField(verbose_name='Ссылка на WhatsApp')),
                ('sidebar_image_1', models.ImageField(upload_to='sidebar/', verbose_name='Изображение кнопки вызова инженера')),
                ('sidebar_image_2', models.ImageField(upload_to='sidebar/', verbose_name='Изображение кнопки скачивания прайса')),
                ('sidebar_image_3', models.ImageField(upload_to='sidebar/', verbose_name='Изображение кнопки WhatsApp')),
                ('sidebar_arrow', models.ImageField(upload_to='sidebar/', verbose_name='Изображение стрелки')),
            ],
            options={
                'verbose_name': 'Контент страницы',
                'verbose_name_plural': 'Контент страниц',
            },
        ),
    ]
