# Generated by Django 5.1.5 on 2025-01-30 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_sidebar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metacontent',
            options={'verbose_name': '01_Метатеги', 'verbose_name_plural': '01_Метатеги'},
        ),
        migrations.AlterModelOptions(
            name='sidebar',
            options={'verbose_name': '02_Sidebar', 'verbose_name_plural': '02_Sidebar'},
        ),
        migrations.AlterField(
            model_name='sidebar',
            name='sidebar_arrow',
            field=models.FileField(upload_to='sidebar/', verbose_name='Изображение стрелки'),
        ),
        migrations.AlterField(
            model_name='sidebar',
            name='sidebar_image_1',
            field=models.FileField(upload_to='sidebar/', verbose_name='Изображение кнопки вызова инженера'),
        ),
        migrations.AlterField(
            model_name='sidebar',
            name='sidebar_image_2',
            field=models.FileField(upload_to='sidebar/', verbose_name='Изображение кнопки скачивания прайса'),
        ),
        migrations.AlterField(
            model_name='sidebar',
            name='sidebar_image_3',
            field=models.FileField(upload_to='sidebar/', verbose_name='Изображение кнопки WhatsApp'),
        ),
    ]
