# Generated by Django 5.1.5 on 2025-01-30 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_metacontent_options_alter_sidebar_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_desktop', models.FileField(upload_to='header/', verbose_name='Фон desktop')),
                ('bg_mobile', models.FileField(upload_to='header/', verbose_name='Фон mobile')),
                ('logo_link', models.CharField(max_length=255, verbose_name='Ссылка логотипа')),
                ('logo_image', models.ImageField(upload_to='header/', verbose_name='Логотип')),
                ('header_text1', models.TextField(verbose_name='Текст1 в шапке')),
                ('header_text2', models.TextField(verbose_name='Текст2 в шапке')),
                ('map_image', models.FileField(upload_to='header/', verbose_name='Изображение карты')),
                ('map_address', models.TextField(verbose_name='Адрес на карте')),
                ('map_link', models.TextField(verbose_name='Ссылка на карту')),
                ('map_link_text', models.TextField(verbose_name='Текст ссылки на карту')),
                ('catalog_link', models.URLField(verbose_name='Ссылка на каталог')),
                ('catalog_link_text', models.URLField(verbose_name='Текст cсылки на каталог')),
                ('messenger_text', models.CharField(max_length=255, verbose_name='Текст для мессенджеров')),
                ('tg_link', models.TextField(verbose_name='Ссылка на телеграм')),
                ('tg_icon', models.FileField(upload_to='header/', verbose_name='Изображение телеграм')),
                ('wa_icon', models.FileField(upload_to='header/', verbose_name='Изображение whatsapp')),
                ('wa_link', models.TextField(verbose_name='Ссылка на whatsapp')),
                ('working_hours', models.TextField(verbose_name='Часы работы')),
                ('phone_link', models.CharField(max_length=20, verbose_name='Ссылка для звонка')),
                ('phone_image', models.FileField(upload_to='header/', verbose_name='Изображение телефона')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('popup_text', models.CharField(max_length=100, verbose_name='Текст popup')),
            ],
            options={
                'verbose_name': '03_Header',
                'verbose_name_plural': '03_Header',
            },
        ),
    ]
