# Generated by Django 5.1.5 on 2025-01-30 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='catalog_link_text',
            field=models.TextField(verbose_name='Текст cсылки на каталог'),
        ),
    ]
