# Generated by Django 5.1.5 on 2025-01-30 05:15

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_header_catalog_link_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='messenger_text',
            field=tinymce.models.HTMLField(max_length=255, verbose_name='Текст для мессенджеров'),
        ),
    ]
