# Generated by Django 5.1.5 on 2025-01-30 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_header_messenger_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='messenger_text',
            field=models.CharField(max_length=255, verbose_name='Текст для мессенджеров'),
        ),
    ]
