# Generated by Django 5.1.5 on 2025-01-30 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_header_messenger_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='header',
            name='messenger_text',
        ),
    ]
