# Generated by Django 5.1.5 on 2025-01-30 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_header_tg_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='logo_image',
            field=models.FileField(upload_to='header/', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='header',
            name='logo_link',
            field=models.URLField(verbose_name='Ссылка логотипа'),
        ),
        migrations.AlterField(
            model_name='header',
            name='map_link',
            field=models.URLField(verbose_name='Ссылка на карту'),
        ),
        migrations.AlterField(
            model_name='header',
            name='wa_link',
            field=models.URLField(verbose_name='Ссылка на whatsapp'),
        ),
    ]
