# Generated by Django 5.1.5 on 2025-01-30 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_header_logo_image_alter_header_logo_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_link', models.URLField(verbose_name='Ссылка на главную')),
                ('main_link_text', models.CharField(max_length=100, verbose_name='Текст ссылки на главную')),
                ('quiz_link_text', models.CharField(max_length=100, verbose_name='Текст ссылки на quiz')),
                ('budget_link_text', models.CharField(max_length=100, verbose_name='Текст ссылки на budget')),
                ('catalog_link', models.URLField(verbose_name='Ссылка на каталог')),
                ('catalog_link_text', models.CharField(max_length=100, verbose_name='Текст ссылки на каталог')),
                ('guarantees_link_text', models.CharField(max_length=100, verbose_name='Текст ссылки на гарантии')),
                ('portfolio_link_text', models.CharField(max_length=100, verbose_name='Текст ссылки на портфолио')),
                ('about_link_text', models.CharField(max_length=100, verbose_name='Текст ссылки о компании')),
                ('quality_link_text', models.CharField(max_length=100, verbose_name='Текст ссылки о quality')),
                ('contacts_link_text', models.CharField(max_length=100, verbose_name='Текст ссылки о contacts')),
            ],
            options={
                'verbose_name': '04_Menu',
                'verbose_name_plural': '04_Menu',
            },
        ),
    ]
