# Generated by Django 5.1.5 on 2025-01-30 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h1', models.TextField(verbose_name='Заголовок')),
                ('check_img', models.FileField(upload_to='main/', verbose_name='Изображение check')),
                ('text_1', models.TextField(verbose_name='Текст 1')),
                ('text_2', models.TextField(verbose_name='Текст 2')),
                ('text_3', models.TextField(verbose_name='Текст 3')),
                ('text_4', models.TextField(verbose_name='Текст 4')),
                ('text_5', models.TextField(verbose_name='Текст 5')),
                ('button_text', models.TextField(verbose_name='Текст кнопки')),
                ('touch_img', models.FileField(upload_to='main/', verbose_name='Изображение touch')),
                ('text_6', models.TextField(verbose_name='Текст 6')),
                ('text_01', models.TextField(verbose_name='Текст 01')),
                ('text_02', models.TextField(verbose_name='Текст 02')),
                ('text_03', models.TextField(verbose_name='Текст 03')),
                ('text_04', models.TextField(verbose_name='Текст 04')),
                ('text_05', models.TextField(verbose_name='Текст 05')),
                ('text_06', models.TextField(verbose_name='Текст 06')),
            ],
            options={
                'verbose_name': '05_Main',
                'verbose_name_plural': '05_Main',
            },
        ),
        migrations.AlterField(
            model_name='menu',
            name='quiz_link_text',
            field=models.CharField(max_length=100, verbose_name='Текст ссылки на акции'),
        ),
    ]
