# Generated by Django 5.1.5 on 2025-01-30 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_add'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_header', models.TextField(verbose_name='Quiz header')),
                ('quiz_header_text1', models.TextField(verbose_name='Quiz header текст1')),
                ('quiz_header_text2', models.TextField(verbose_name='Quiz header текст2')),
                ('quiz_header_text3', models.TextField(verbose_name='Quiz header текст3')),
                ('quiz_line_text1', models.TextField(verbose_name='Quiz line текст1')),
                ('quiz_question1_title', models.TextField(verbose_name='Quiz question1 title')),
                ('quiz_question1_1_img', models.FileField(upload_to='quiz/', verbose_name='Quiz первый вопрос первый вариант ответа изображение')),
                ('quiz_question1_1_text', models.TextField(verbose_name='Quiz первый вопрос первый вариант ответа текст')),
                ('quiz_question1_2_img', models.FileField(upload_to='quiz/', verbose_name='Quiz первый вопрос второй вариант ответа изображение')),
                ('quiz_question1_2_text', models.TextField(verbose_name='Quiz первый вопрос второй вариант ответа текст')),
                ('quiz_question1_3_img', models.FileField(upload_to='quiz/', verbose_name='Quiz первый вопрос третий вариант ответа изображение')),
                ('quiz_question1_3_text', models.TextField(verbose_name='Quiz первый вопрос третий вариант ответа текст')),
                ('quiz_question2_title', models.TextField(verbose_name='Quiz второй вопрос заголовок')),
                ('quiz_question2_1', models.TextField(verbose_name='Quiz второй вопрос первый вариант ответа')),
                ('quiz_question2_2', models.TextField(verbose_name='Quiz второй вопрос второй вариант ответа')),
                ('quiz_question2_3', models.TextField(verbose_name='Quiz второй вопрос третий вариант ответа')),
                ('quiz_question2_4', models.TextField(verbose_name='Quiz второй вопрос четвёртый вариант ответа')),
                ('quiz_question3_title', models.TextField(verbose_name='Quiz третий вопрос заголовок')),
                ('quiz_question3_1_text', models.TextField(verbose_name='Quiz третий вопрос первый вариант ответа текст')),
                ('quiz_question3_1_hint', models.TextField(verbose_name='Quiz третий вопрос первый вариант ответа hint')),
                ('quiz_question3_2_text', models.TextField(verbose_name='Quiz третий вопрос второй вариант ответа текст')),
                ('quiz_question3_2_hint', models.TextField(verbose_name='Quiz третий вопрос второй вариант ответа hint')),
                ('quiz_question3_3_text', models.TextField(verbose_name='Quiz третий вопрос третий вариант ответа текст')),
                ('quiz_question3_3_hint', models.TextField(verbose_name='Quiz третий вопрос третий вариант ответа hint')),
                ('quiz_question3_4_text', models.TextField(verbose_name='Quiz третий вопрос четвёртый вариант ответа текст')),
                ('quiz_question3_4_hint', models.TextField(verbose_name='Quiz третий вопрос четвёртый вариант ответа hint')),
                ('quiz_question4_title', models.TextField(verbose_name='Quiz четвёртый вопрос заголовок')),
                ('quiz_question4_1', models.TextField(verbose_name='Quiz четвёртый вопрос первый вариант ответа')),
                ('quiz_question4_2', models.TextField(verbose_name='Quiz четвёртый вопрос второй вариант ответа')),
                ('touch_img', models.FileField(upload_to='quiz/', verbose_name='Изображение touch')),
                ('touch_text', models.TextField(verbose_name='Текст touch')),
                ('button_text1', models.TextField(verbose_name='Текст кнопки1')),
                ('button_text2', models.TextField(verbose_name='Текст кнопки2')),
                ('quiz_right_bg', models.FileField(upload_to='quiz/', verbose_name='Quiz right изображение bg')),
                ('quiz_right_text1', models.TextField(verbose_name='Quiz right текст 1')),
                ('quiz_right_text2', models.TextField(verbose_name='Quiz right текст 2')),
                ('quiz_right_text3', models.TextField(verbose_name='Quiz right текст 3')),
                ('quiz_load_img', models.FileField(upload_to='quiz/', verbose_name='Quiz load изображение')),
                ('quiz_load_text', models.TextField(verbose_name='Quiz load текст')),
                ('quiz_result_bg', models.FileField(upload_to='quiz/', verbose_name='Quiz result изображение bg')),
                ('quiz_result_title', models.TextField(verbose_name='Quiz result заголовок')),
                ('quiz_result_subtitle', models.TextField(verbose_name='Quiz result subtitle')),
                ('quiz_result_text', models.TextField(verbose_name='Quiz result text')),
                ('quiz_result_wa', models.FileField(upload_to='quiz/', verbose_name='Quiz result изображение wa')),
                ('quiz_result_tg', models.FileField(upload_to='quiz/', verbose_name='Quiz result изображение tg')),
                ('quiz_result_btn_text', models.TextField(verbose_name='Quiz result btn text')),
                ('quiz_result_wa_text', models.TextField(verbose_name='Quiz result wa text')),
                ('quiz_result_tg_text', models.TextField(verbose_name='Quiz result tg text')),
                ('quiz_result_btn_text2', models.TextField(verbose_name='Quiz result btn text2')),
                ('quiz_result_check', models.FileField(upload_to='quiz/', verbose_name='Quiz result изображение check')),
                ('quiz_result_check_text', models.TextField(verbose_name='Quiz result check text')),
            ],
            options={
                'verbose_name': '07_Quiz',
                'verbose_name_plural': '07_Quiz',
            },
        ),
    ]
