# Generated by Django 5.1.5 on 2025-01-30 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_quiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.TextField(verbose_name='Header')),
                ('swipe_text', models.TextField(verbose_name='Swipe text')),
                ('swipe_img', models.FileField(upload_to='categories/', verbose_name='Swipe изображение')),
                ('arrow_img', models.FileField(upload_to='categories/', verbose_name='Arrow изображение')),
                ('manufacturer2_img', models.FileField(upload_to='categories/', verbose_name='Manufacturer 2 изображение')),
                ('manufacturer1_img', models.FileField(upload_to='categories/', verbose_name='Manufacturer 1 изображение')),
                ('manufacturer3_img', models.FileField(upload_to='categories/', verbose_name='Manufacturer 3 изображение')),
                ('manufacturer8_img', models.FileField(upload_to='categories/', verbose_name='Manufacturer 8 изображение')),
                ('manufacturer6_img', models.FileField(upload_to='categories/', verbose_name='Manufacturer 6 изображение')),
                ('manufacturer4_img', models.FileField(upload_to='categories/', verbose_name='Manufacturer 4 изображение')),
                ('manufacturer5_img', models.FileField(upload_to='categories/', verbose_name='Manufacturer 5 изображение')),
                ('manufacturer7_img', models.FileField(upload_to='categories/', verbose_name='Manufacturer 7 изображение')),
                ('manufacturer9_img', models.FileField(upload_to='categories/', verbose_name='Manufacturer 9 изображение')),
                ('manufacturer10_img', models.FileField(upload_to='categories/', verbose_name='Manufacturer 10 изображение')),
            ],
            options={
                'verbose_name': '08_Category',
                'verbose_name_plural': '08_Categories',
            },
        ),
    ]
