# Generated by Django 5.1.5 on 2025-01-31 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelDynamic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer_number_d', models.IntegerField(verbose_name='Номер производителя')),
                ('model_number_d', models.IntegerField(verbose_name='Номер модели')),
                ('name_d', models.TextField(verbose_name='Название')),
                ('image_d', models.FileField(upload_to='mod/', verbose_name='Изображение')),
                ('description_d', models.TextField(verbose_name='Описание')),
                ('char1_key_d', models.TextField(verbose_name='Характеристика 1 ключ')),
                ('char1_value_d', models.TextField(verbose_name='Характеристика 1 значение')),
                ('char2_key_d', models.TextField(verbose_name='Характеристика 2 ключ')),
                ('char2_value_d', models.TextField(verbose_name='Характеристика 2 значение')),
                ('char3_key_d', models.TextField(verbose_name='Характеристика 3 ключ')),
                ('char3_value_d', models.TextField(verbose_name='Характеристика 3 значение')),
                ('char4_key_d', models.TextField(verbose_name='Характеристика 4 ключ')),
                ('char4_value_d', models.TextField(verbose_name='Характеристика 4 значение')),
                ('available_d', models.TextField(verbose_name='Наличие')),
                ('discount_d', models.TextField(verbose_name='Скидка')),
                ('body_guarantee_d', models.TextField(verbose_name='Гарантия на корпус')),
                ('installation_guarantee_d', models.TextField(verbose_name='Гарантия на монтаж')),
                ('price_new_d', models.TextField(verbose_name='Новая цена')),
                ('price_old_d', models.TextField(verbose_name='Старая цена')),
            ],
            options={
                'verbose_name': '10 Модели',
                'verbose_name_plural': '10 Модели',
            },
        ),
        migrations.CreateModel(
            name='ModelStatic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_description_s', models.TextField(verbose_name='Заголовок описания')),
                ('title_char_s', models.TextField(verbose_name='Заголовок характеристик')),
                ('text_btn_s', models.TextField(verbose_name='Текст кнопки')),
                ('hint_key_s', models.TextField(verbose_name='Hint вопрос')),
                ('hint_value_s', models.TextField(verbose_name='Hint ответ')),
                ('installment_s', models.TextField(verbose_name='Рассрочка')),
                ('delivery_s', models.TextField(verbose_name='Доставка')),
                ('wa_text_s', models.TextField(verbose_name='Текст WhatsApp')),
                ('wa_link_s', models.URLField(verbose_name='Ссылка WhatsApp')),
                ('ya_map_title', models.TextField(verbose_name='Заголовок яндекс карт')),
                ('ya_map_link', models.URLField(verbose_name='Ссылка яндекс карт')),
                ('ya_map_btn', models.TextField(verbose_name='Кнопка яндекс карт')),
            ],
            options={
                'verbose_name': '09 Модели статика',
                'verbose_name_plural': '09 Модели статика',
            },
        ),
        migrations.AlterModelOptions(
            name='add',
            options={'verbose_name': '06 Дополнительные услуги', 'verbose_name_plural': '06 Дополнительные услуги'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '08 Производители', 'verbose_name_plural': '08 Производители'},
        ),
        migrations.AlterModelOptions(
            name='header',
            options={'verbose_name': '03 Шапка', 'verbose_name_plural': '03 Шапка'},
        ),
        migrations.AlterModelOptions(
            name='maincontent',
            options={'verbose_name': '05 Первый экран', 'verbose_name_plural': '05 Первый экран'},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': '04 Меню', 'verbose_name_plural': '04 Меню'},
        ),
        migrations.AlterModelOptions(
            name='metacontent',
            options={'verbose_name': '01 Метатеги', 'verbose_name_plural': '01 Метатеги'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name': '07 Квиз', 'verbose_name_plural': '07 Квиз'},
        ),
        migrations.AlterModelOptions(
            name='sidebar',
            options={'verbose_name': '02 Сайдбар', 'verbose_name_plural': '02 Сайдбар'},
        ),
    ]
