# Generated by Django 5.1.5 on 2025-01-31 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_modeldynamic_modelstatic_alter_add_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_bg_desktop', models.FileField(upload_to='catalog/', verbose_name='Изображение фона desktop')),
                ('image_bg_mobile', models.FileField(upload_to='catalog/', verbose_name='Изображение фона mobile')),
                ('title', models.TextField(verbose_name='Заголовок')),
                ('title_h2', models.TextField(verbose_name='Заголовок h2')),
                ('update', models.TextField(verbose_name='Update')),
                ('btn_wa', models.TextField(verbose_name='Кнопка wa')),
                ('wa_text', models.TextField(verbose_name='Текст wa')),
                ('tg_text', models.TextField(verbose_name='Текст tg')),
                ('btn', models.TextField(verbose_name='Кнопка')),
                ('politic', models.TextField(verbose_name='Политика конфиденциальности')),
            ],
            options={
                'verbose_name': '10 Каталог',
                'verbose_name_plural': '10 Каталог',
            },
        ),
    ]
