# Generated by Django 5.1.5 on 2025-01-31 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_budget_alter_catalog_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guarantees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_1', models.FileField(upload_to='guarantees/', verbose_name='Фон 1 изображение')),
                ('number', models.FileField(upload_to='guarantees/', verbose_name='Число')),
                ('text', models.TextField(verbose_name='Текст')),
                ('bg_2', models.FileField(upload_to='guarantees/', verbose_name='Фон 2 изображение')),
                ('mobile', models.FileField(upload_to='guarantees/', verbose_name='Mobile изображение')),
                ('h2', models.TextField(verbose_name='Текст h2')),
            ],
            options={
                'verbose_name': '13 Гарантии',
                'verbose_name_plural': '13 Гарантии',
            },
        ),
    ]
