# Generated by Django 5.1.5 on 2025-01-31 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_text', models.TextField(verbose_name='Текст шапки')),
                ('swipe_text', models.TextField(verbose_name='Swipe текст')),
                ('block1_img_main', models.FileField(upload_to='portfolio/', verbose_name='Блок 1 изображение главное')),
                ('block1_img2', models.FileField(upload_to='portfolio/', verbose_name='Блок 1 изображение 2')),
                ('block1_img3', models.FileField(upload_to='portfolio/', verbose_name='Блок 1 изображение 3')),
                ('block1_img4', models.FileField(upload_to='portfolio/', verbose_name='Блок 1 изображение 4')),
                ('block1_img5', models.FileField(upload_to='portfolio/', verbose_name='Блок 1 изображение 5')),
                ('block1_title', models.TextField(verbose_name='Блок 1 заголовок')),
                ('block1_address', models.TextField(verbose_name='Блок 1 адрес')),
                ('block2_img_main', models.FileField(upload_to='portfolio/', verbose_name='Блок 2 изображение главное')),
                ('block2_img2', models.FileField(upload_to='portfolio/', verbose_name='Блок 2 изображение 2')),
                ('block2_img3', models.FileField(upload_to='portfolio/', verbose_name='Блок 2 изображение 3')),
                ('block2_img4', models.FileField(upload_to='portfolio/', verbose_name='Блок 2 изображение 4')),
                ('block2_img5', models.FileField(upload_to='portfolio/', verbose_name='Блок 2 изображение 5')),
                ('block2_title', models.TextField(verbose_name='Блок 2 заголовок')),
                ('block2_address', models.TextField(verbose_name='Блок 2 адрес')),
                ('block3_img_main', models.FileField(upload_to='portfolio/', verbose_name='Блок 3 изображение главное')),
                ('block3_img2', models.FileField(upload_to='portfolio/', verbose_name='Блок 3 изображение 2')),
                ('block3_img3', models.FileField(upload_to='portfolio/', verbose_name='Блок 3 изображение 3')),
                ('block3_img4', models.FileField(upload_to='portfolio/', verbose_name='Блок 3 изображение 4')),
                ('block3_img5', models.FileField(upload_to='portfolio/', verbose_name='Блок 3 изображение 5')),
                ('block3_title', models.TextField(verbose_name='Блок 3 заголовок')),
                ('block3_address', models.TextField(verbose_name='Блок 3 адрес')),
                ('block4_img_main', models.FileField(upload_to='portfolio/', verbose_name='Блок 4 изображение главное')),
                ('block4_img2', models.FileField(upload_to='portfolio/', verbose_name='Блок 4 изображение 2')),
                ('block4_img3', models.FileField(upload_to='portfolio/', verbose_name='Блок 4 изображение 3')),
                ('block4_img4', models.FileField(upload_to='portfolio/', verbose_name='Блок 4 изображение 4')),
                ('block4_img5', models.FileField(upload_to='portfolio/', verbose_name='Блок 4 изображение 5')),
                ('block4_title', models.TextField(verbose_name='Блок 4 заголовок')),
                ('block4_address', models.TextField(verbose_name='Блок 4 адрес')),
                ('block5_img_main', models.FileField(upload_to='portfolio/', verbose_name='Блок 5 изображение главное')),
                ('block5_img2', models.FileField(upload_to='portfolio/', verbose_name='Блок 5 изображение 2')),
                ('block5_img3', models.FileField(upload_to='portfolio/', verbose_name='Блок 5 изображение 3')),
                ('block5_img4', models.FileField(upload_to='portfolio/', verbose_name='Блок 5 изображение 4')),
                ('block5_img5', models.FileField(upload_to='portfolio/', verbose_name='Блок 5 изображение 5')),
                ('block5_title', models.TextField(verbose_name='Блок 5 заголовок')),
                ('block5_address', models.TextField(verbose_name='Блок 5 адрес')),
            ],
            options={
                'verbose_name': '15 Портфолио',
                'verbose_name_plural': '15 Портфолио',
            },
        ),
    ]
