# Generated by Django 5.1.5 on 2025-01-31 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_text', models.TextField(verbose_name='Текст шапки')),
                ('youtube_link1', models.URLField(verbose_name='Ссылка youtube 1')),
                ('youtube_link2', models.URLField(verbose_name='Ссылка youtube 2')),
                ('text', models.TextField(verbose_name='Текст')),
                ('swipe_text', models.TextField(verbose_name='Swipe текст')),
                ('youtube_shorts', models.URLField(verbose_name='Ссылка youtube shorts')),
                ('img', models.FileField(upload_to='video/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': '16 Видео',
                'verbose_name_plural': '16 Видео',
            },
        ),
    ]
