# Generated by Django 5.1.5 on 2025-01-31 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg', models.FileField(upload_to='reviews/', verbose_name='Фон')),
                ('header_text', models.TextField(verbose_name='Текст шапки')),
                ('img1', models.FileField(upload_to='reviews/', verbose_name='Изображение 1')),
                ('img2', models.FileField(upload_to='reviews/', verbose_name='Изображение 2')),
                ('img3', models.FileField(upload_to='reviews/', verbose_name='Изображение 3')),
                ('img4', models.FileField(upload_to='reviews/', verbose_name='Изображение 4')),
                ('img5', models.FileField(upload_to='reviews/', verbose_name='Изображение 5')),
                ('img6', models.FileField(upload_to='reviews/', verbose_name='Изображение 6')),
                ('img7', models.FileField(upload_to='reviews/', verbose_name='Изображение 7')),
                ('rate', models.TextField(verbose_name='Рейтинг')),
                ('text', models.TextField(verbose_name='Текст')),
                ('ya_map_link', models.URLField(verbose_name='Ссылка на yandex карту')),
                ('text2', models.TextField(verbose_name='Текст 2')),
                ('bg2', models.FileField(upload_to='reviews/', verbose_name='Фон 2')),
                ('bg_mobile', models.FileField(upload_to='reviews/', verbose_name='Фон mobile')),
                ('header_text2', models.TextField(verbose_name='Текст шапки 2')),
                ('subtitle_text', models.TextField(verbose_name='Текст подзаголовок')),
                ('text3', models.TextField(verbose_name='Текст 3')),
                ('wa_link', models.URLField(verbose_name='Ссылка на whatsapp')),
                ('text4', models.TextField(verbose_name='Текст 4')),
            ],
            options={
                'verbose_name': '17 Отзывы',
                'verbose_name_plural': '17 Отзывы',
            },
        ),
    ]
