# Generated by Django 5.1.5 on 2025-01-31 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='Install',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg', models.FileField(upload_to='install/', verbose_name='Фон')),
                ('bg_mobile', models.FileField(upload_to='install/', verbose_name='Фон mobile')),
                ('header_text', models.TextField(verbose_name='Текст шапки')),
                ('subtitle', models.TextField(verbose_name='Подзаголовок')),
                ('swipe_text', models.TextField(verbose_name='Swipe текст')),
                ('img1', models.FileField(upload_to='install/', verbose_name='Изображение 1')),
                ('text1', models.TextField(verbose_name='Текст 1')),
                ('img2', models.FileField(upload_to='install/', verbose_name='Изображение 2')),
                ('text2', models.TextField(verbose_name='Текст 2')),
                ('img3', models.FileField(upload_to='install/', verbose_name='Изображение 3')),
                ('text3', models.TextField(verbose_name='Текст 3')),
                ('img4', models.FileField(upload_to='install/', verbose_name='Изображение 4')),
                ('text4', models.TextField(verbose_name='Текст 4')),
                ('img5', models.FileField(upload_to='install/', verbose_name='Изображение 5')),
                ('text5', models.TextField(verbose_name='Текст 5')),
                ('img6', models.FileField(upload_to='install/', verbose_name='Изображение 6')),
                ('text6', models.TextField(verbose_name='Текст 6')),
                ('title_right1', models.TextField(verbose_name='Заголовок справа 1')),
                ('text_right1', models.TextField(verbose_name='Текст справа 1')),
                ('title_right2', models.TextField(verbose_name='Заголовок справа 2')),
                ('text_right2', models.TextField(verbose_name='Текст справа 2')),
            ],
            options={
                'verbose_name': '18 Установка',
                'verbose_name_plural': '18 Установка',
            },
        ),
    ]
