# Generated by Django 5.1.5 on 2025-02-01 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_install'),
    ]

    operations = [
        migrations.CreateModel(
            name='Numbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.TextField(verbose_name='Заголовок 1')),
                ('text1', models.TextField(verbose_name='Текст 1')),
                ('title2', models.TextField(verbose_name='Заголовок 2')),
                ('text2', models.TextField(verbose_name='Текст 2')),
                ('title3', models.TextField(verbose_name='Заголовок 3')),
                ('text3', models.TextField(verbose_name='Текст 3')),
                ('title4', models.TextField(verbose_name='Заголовок 4')),
                ('text4', models.TextField(verbose_name='Текст 4')),
                ('montage_img1', models.FileField(upload_to='numbers/', verbose_name='Изображение 1')),
                ('montage_header1', models.TextField(verbose_name='Header 1')),
                ('montage_number1', models.TextField(verbose_name='Номер 1')),
                ('montage_text1', models.TextField(verbose_name='Текст 1')),
                ('montage_img2', models.FileField(upload_to='numbers/', verbose_name='Изображение 2')),
                ('montage_header2', models.TextField(verbose_name='Header 2')),
                ('montage_number2', models.TextField(verbose_name='Номер 2')),
                ('montage_text2', models.TextField(verbose_name='Текст 2')),
                ('montage_img3', models.FileField(upload_to='numbers/', verbose_name='Изображение 3')),
                ('montage_header3', models.TextField(verbose_name='Header 3')),
                ('montage_number3', models.TextField(verbose_name='Номер 3')),
                ('montage_text3', models.TextField(verbose_name='Текст 3')),
                ('montage_img4', models.FileField(upload_to='numbers/', verbose_name='Изображение 4')),
                ('montage_header4', models.TextField(verbose_name='Header 4')),
                ('montage_number4', models.TextField(verbose_name='Номер 4')),
                ('montage_text4', models.TextField(verbose_name='Текст 4')),
                ('montage_img5', models.FileField(upload_to='numbers/', verbose_name='Изображение 5')),
                ('montage_header5', models.TextField(verbose_name='Header 5')),
                ('montage_number5', models.TextField(verbose_name='Номер 5')),
                ('montage_text5', models.TextField(verbose_name='Текст 5')),
            ],
            options={
                'verbose_name': '19 Цифры',
                'verbose_name_plural': '19 Цифры',
            },
        ),
    ]
