# Generated by Django 5.1.5 on 2025-02-01 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_numbers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg', models.FileField(upload_to='quality/', verbose_name='Фон')),
                ('header_text', models.TextField(verbose_name='Текст шапки')),
                ('swipe_text', models.TextField(verbose_name='Swipe текст')),
                ('number1', models.TextField(verbose_name='Номер 1')),
                ('title1', models.TextField(verbose_name='Заголовок 1')),
                ('text1_1', models.TextField(verbose_name='Текст 1_1')),
                ('text1_2', models.TextField(verbose_name='Текст 1_2')),
                ('title2', models.TextField(verbose_name='Заголовок 2')),
                ('text2_1', models.TextField(verbose_name='Текст 2_1')),
                ('text2_2', models.TextField(verbose_name='Текст 2_2')),
                ('title3', models.TextField(verbose_name='Заголовок 3')),
                ('text3_1', models.TextField(verbose_name='Текст 3_1')),
                ('text3_2', models.TextField(verbose_name='Текст 3_2')),
                ('bg2', models.FileField(upload_to='quality/', verbose_name='Фон 2')),
                ('bg_mobile', models.FileField(upload_to='quality/', verbose_name='Фон mobile')),
                ('report_header', models.TextField(verbose_name='Текст шапки')),
                ('report_text', models.TextField(verbose_name='Текст')),
            ],
            options={
                'verbose_name': '20 Качество',
                'verbose_name_plural': '20 Качество',
            },
        ),
    ]
