# Generated by Django 5.1.5 on 2025-02-01 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_quality'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_text', models.TextField(verbose_name='Текст шапки')),
                ('question1', models.TextField(verbose_name='Вопрос 1')),
                ('answer1', models.TextField(verbose_name='Ответ 1')),
                ('question2', models.TextField(verbose_name='Вопрос 2')),
                ('answer2', models.TextField(verbose_name='Ответ 2')),
                ('question3', models.TextField(verbose_name='Вопрос 3')),
                ('answer3', models.TextField(verbose_name='Ответ 3')),
                ('question4', models.TextField(verbose_name='Вопрос 4')),
                ('answer4', models.TextField(verbose_name='Ответ 4')),
                ('question5', models.TextField(verbose_name='Вопрос 5')),
                ('answer5', models.TextField(verbose_name='Ответ 5')),
                ('question6', models.TextField(verbose_name='Вопрос 6')),
                ('answer6', models.TextField(verbose_name='Ответ 6')),
                ('question7', models.TextField(verbose_name='Вопрос 7')),
                ('answer7', models.TextField(verbose_name='Ответ 7')),
                ('question8', models.TextField(verbose_name='Вопрос 8')),
                ('answer8', models.TextField(verbose_name='Ответ 8')),
                ('question9', models.TextField(verbose_name='Вопрос 9')),
                ('answer9', models.TextField(verbose_name='Ответ 9')),
                ('question10', models.TextField(verbose_name='Вопрос 10')),
                ('answer10', models.TextField(verbose_name='Ответ 10')),
                ('wa_link', models.URLField(verbose_name='Ссылка на whatsapp')),
                ('wa_text', models.TextField(verbose_name='Текст whatsapp')),
            ],
            options={
                'verbose_name': '21 Вопрос-ответ',
                'verbose_name_plural': '21 Вопрос-ответ',
            },
        ),
    ]
