# Generated by Django 5.1.5 on 2025-02-01 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_text', models.TextField(verbose_name='Текст шапки')),
                ('title', models.TextField(verbose_name='Заголовок')),
                ('bg', models.FileField(upload_to='requisition/', verbose_name='Фон')),
                ('bg_mobile', models.FileField(upload_to='requisition/', verbose_name='Фон mobile')),
                ('title2', models.TextField(verbose_name='Заголовок 2')),
                ('text1', models.TextField(verbose_name='Текст 1')),
                ('text2', models.TextField(verbose_name='Текст 2')),
                ('text3', models.TextField(verbose_name='Текст 3')),
                ('text4', models.TextField(verbose_name='Текст 4')),
                ('text5', models.TextField(verbose_name='Текст 5')),
                ('text6', models.TextField(verbose_name='Текст 6')),
                ('title3', models.TextField(verbose_name='Заголовок 3')),
                ('btn', models.TextField(verbose_name='Кнопка текст')),
                ('text7', models.TextField(verbose_name='Текст 7')),
                ('text8', models.TextField(verbose_name='Текст 8')),
                ('text9', models.TextField(verbose_name='Текст 9')),
            ],
            options={
                'verbose_name': '22 Заявка',
                'verbose_name_plural': '22 Заявка',
            },
        ),
    ]
