# Generated by Django 5.1.5 on 2025-02-01 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_requisition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_text', models.TextField(verbose_name='Текст шапки')),
                ('title', models.TextField(verbose_name='Заголовок')),
                ('ya_map_link', models.URLField(verbose_name='Ссылка на yandex карту')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('title2', models.TextField(verbose_name='Заголовок 2')),
                ('phone_link', models.URLField(verbose_name='Ссылка на телефон')),
                ('phone', models.TextField(verbose_name='Телефон')),
                ('wa_link', models.URLField(verbose_name='Ссылка на whatsapp')),
                ('tg_link', models.URLField(verbose_name='Ссылка на telegram')),
                ('vk_link', models.URLField(verbose_name='Ссылка на vk')),
                ('title3', models.TextField(verbose_name='Заголовок 3')),
                ('email_link', models.TextField(verbose_name='Ссылка email')),
                ('email_text', models.TextField(verbose_name='Текст email')),
                ('title4', models.TextField(verbose_name='Заголовок 4')),
                ('text', models.TextField(verbose_name='Текст')),
                ('title5', models.TextField(verbose_name='Заголовок 5')),
                ('swipe_text', models.TextField(verbose_name='Swipe text')),
                ('slider1_img1', models.FileField(upload_to='contacts/', verbose_name='Слайдер 1 изображение 1')),
                ('slider1_text1', models.TextField(verbose_name='Слайдер 1 текст 1')),
                ('slider1_img2', models.FileField(upload_to='contacts/', verbose_name='Слайдер 1 изображение 2')),
                ('slider1_text2', models.TextField(verbose_name='Слайдер 1 текст 2')),
                ('slider1_img3', models.FileField(upload_to='contacts/', verbose_name='Слайдер 1 изображение 3')),
                ('slider1_text3', models.TextField(verbose_name='Слайдер 1 текст 3')),
                ('slider2_img1', models.FileField(upload_to='contacts/', verbose_name='Слайдер 2 изображение 1')),
                ('slider2_text1', models.TextField(verbose_name='Слайдер 2 текст 1')),
                ('slider2_img2', models.FileField(upload_to='contacts/', verbose_name='Слайдер 2 изображение 2')),
                ('slider2_text2', models.TextField(verbose_name='Слайдер 2 текст 2')),
                ('title6', models.TextField(verbose_name='Заголовок 6')),
                ('yandex_map', models.TextField(verbose_name='Яндекс карта')),
            ],
            options={
                'verbose_name': '23 Контакты',
                'verbose_name_plural': '23 Контакты',
            },
        ),
    ]
