# Generated by Django 5.1.5 on 2025-02-01 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_contacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_link', models.TextField(verbose_name='Ссылка на логотипе')),
                ('logo_img', models.FileField(upload_to='footer/', verbose_name='Логотип изображение')),
                ('text1', models.TextField(verbose_name='Текст 1')),
                ('text2', models.TextField(verbose_name='Текст 2')),
                ('text3', models.TextField(verbose_name='Текст 3')),
            ],
            options={
                'verbose_name': '24 Футер',
                'verbose_name_plural': '24 Футер',
            },
        ),
        migrations.AlterField(
            model_name='contacts',
            name='phone_link',
            field=models.TextField(verbose_name='Ссылка на телефон'),
        ),
    ]
