# Generated by Django 5.1.5 on 2025-02-01 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_footer_alter_contacts_phone_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopupRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg', models.FileField(upload_to='popup_request/', verbose_name='Фон')),
                ('title', models.TextField(verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
                ('btn', models.TextField(verbose_name='Кнопка')),
                ('text2', models.TextField(verbose_name='Текст 2')),
            ],
            options={
                'verbose_name': '25 Всплывающее окно заявка',
                'verbose_name_plural': '25 Всплывающее окно заявка',
            },
        ),
    ]
