# Generated by Django 5.1.5 on 2025-02-01 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_popuprequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopupStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg', models.FileField(upload_to='popup_stock/', verbose_name='Фон')),
                ('header', models.TextField(verbose_name='Текст в шапке')),
                ('title', models.TextField(verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
                ('btn', models.TextField(verbose_name='Кнопка')),
                ('text2', models.TextField(verbose_name='Текст 2')),
            ],
            options={
                'verbose_name': '26 Всплывающее окно акции',
                'verbose_name_plural': '26 Всплывающее окно акции',
            },
        ),
    ]
