# Generated by Django 5.1.5 on 2025-02-01 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_popuppolitic'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopupLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg', models.FileField(upload_to='popup_leave/', verbose_name='Фон')),
                ('header', models.TextField(verbose_name='Текст в шапке')),
                ('text', models.TextField(verbose_name='Текст')),
                ('title', models.TextField(verbose_name='Заголовок')),
                ('text2', models.TextField(verbose_name='Текст 2')),
                ('btn', models.TextField(verbose_name='Кнопка')),
                ('wa_text', models.TextField(verbose_name='Whatsapp')),
                ('tg_text', models.TextField(verbose_name='Telegram')),
                ('btn2', models.TextField(verbose_name='Кнопка 2')),
                ('text3', models.TextField(verbose_name='Текст 3')),
            ],
            options={
                'verbose_name': '28 Всплывающее окно подождите',
                'verbose_name_plural': '28 Всплывающее окно подождите',
            },
        ),
    ]
